POST /request
Host: localhost:8000
Content-Type: application/json

{
  "firstname": "Leo",
  "lastname": "Petrov",
  "middlename": "Petrovich",
  "phone": "+79091234567",
  "email": "ivan@mail.ru"
}

###

GET /request/61b5d31f-68f2-438c-b0bf-26244d8f963b
Host: localhost:8000

###

GET /request
Host: localhost:8000

###
