POST /request
Host: localhost:8000
Content-Type: application/json

{
  "firstname": "Petr",
  "lastname": "Petrov",
  "middlename": "Petrovich",
  "phone": "+79091234567",
  "email": "ivan@mail.ru"
}

<> 2019-12-12T122557.201.json
<> 2019-12-12T122352.201.json

###

GET /request/3285acd5-6dd5-437c-9fae-9309925446f1
Host: localhost:8000

###

GET /request
Host: localhost:8000

###
